version: '3.9'

services:
  pawsavers-api:
    container_name: pawsavers-api
    env_file:
      - ".env"
    image: ${IMAGE_NAME}:${IMAGE_VERSION}
    build: .
    ports:
      - "${PORT}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - pawsavers_db

  pawsavers_db:
    container_name: pawsavers_db
    env_file:
      - ".env"
    image: postgres:${POSTGRES_VERSION}
    volumes:
      - ${POSTGRES_VOLUME}
    ports:
      - "${POSTGRES_PORT}"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  pgadmin:
    container_name: pgadmin
    env_file:
      - ".env"
    image: dpage/pgadmin4
    volumes:
      - ${PGADMIN_VOLUME_NAME}:${PGADMIN_VOLUME_URL}
    ports:
      - "${PGADMIN_PORT}"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
